### ISSUE TITLE
Impacted by 2022.07 / bluepy / pybluez?

### ISSUE THREAD

**Issue by autumnwalker** [mjmccans/hassio-addon-airthings#15]
Hello - do we know if this addon is impacted by the Python 3.10 update in 2022.07?

I understand two of the major python libraries are not supporting 3.10 (bluepy / pybluez) - unclear if this addon relies on either of these.

edit: my rudimentary code search / understanding seems like this relies on bluepy and therefore will not work in 2022.07.

**Comment by mjmccans** [comment]
It will not be impacted because the addon runs in its own docker container that will continue to include bluepy, and I have upgraded to 2022.7 on my own system and the addon has continued to work. However, last night I started looking into moving over to bleak instead of bluepy, but it may take me a bit of time to figure it out.

**Comment by autumnwalker** [comment]
Great news, thank you!

**Comment by autumnwalker** [comment]
Great, thanks!
