### ISSUE TITLE
Cannot install bleak==0.14.3 because these packages versions have conflicting dependencies.

### ISSUE THREAD

**Issue by mboisson** [mjmccans/hassio-addon-airthings#23]
When trying to reload home assistant with airthings_wave installed... 

Error executing service: <ServiceCall homeassistant.restart (c:01GGT36F67HH514Z0J26ESNJ52)>
1:20:22 PM – (ERROR) components/homeassistant/__init__.py - message first occurred at 1:18:14 PM and shows up 3 times
The system cannot restart because the configuration is not valid: Platform error sensor.airthings_wave - Requirements for airthings_wave not found: ['bleak==0.14.3'].
1:20:22 PM – (ERROR) Home Assistant Core Integration - message first occurred at 1:18:14 PM and shows up 4 times
Unable to install package bleak==0.14.3: ERROR: Cannot install bleak==0.14.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
1:20:22 PM – (ERROR) util/package.py - message first occurred at 1:18:07 PM and shows up 12 times

**Comment by mjmccans** [comment]
I think you may have the wrong repository because this addon runs in a container and does not share the system bleak library, and it is also not called "airthings_wave". Did you perhaps mean the [airthings_wave](https://github.com/custom-components/sensor.airthings_wave) custom component? Either way, Home Assistant Core 2022.11 that I believe is being released tomorrow is going to include native support for Airthings devices over bluetooth, which renders both my addon and the airthings_wave custom component obsolete, so you may be better off waiting a day or two and trying that out for what I believe will be a better and smoother experience. I hope this helps.

**Comment by mboisson** [comment]
Yes, I thought they were the same thing, I did install through the custom components. 

I guess I will wait. I run HA from a Docker container on Linux. Not sure how this new version will happen, but I'll wait and see

**Comment by mboisson** [comment]
And there's already an issue opened about this https://github.com/custom-components/sensor.airthings_wave/issues/93
